stages:
  - lint
  - test
  - deploy

variables:
  LANG: 'en_us.UTF-8'
  LANGUAGE: 'en_us.UTF-8'
  LC_ALL: 'en_us.UTF-8'

lint:
  stage: lint
  tags:
    - ios
  script:
    - fastlane lint
  only:
    - dev
    - master
  except:
    - /^(\[SKIP-CI\]).*$/

test:
  stage: test
  tags:
    - ios
  script:
    - bundle exec fastlane test
  only:
    - dev
    - master
  except:
    - /^(\[SKIP-CI\]).*$/

staging:
  stage: deploy
  tags:
    - ios
  script:
    - 'fastlane provision --env staging'
    - 'fastlane build ci:true --env staging'
    - 'fastlane distribute method:staging --env staging'
  only:
    - dev
  except:
    - /^(\[SKIP-CI\]).*$/

production:
  stage: deploy
  tags:
    - ios
  script:
    - 'fastlane provision --env prod'
    - 'fastlane build ci:true --env prod'
    - 'fastlane distribute method:production --env prod'
  only:
    - master
