#
# This is a general Fastfile, following this structure:
# - Lint
# - Test
# - Build
# - Distribute
#
# Feel free to add modifications to your specific Fastfile as necessary.
# 

default_platform :ios

platform :ios do 

  lane :lint do
    swiftlint
  end

  lane :test do
    run_tests
  end

  lane :build do
    match
    gym
  end

  lane :distribute do
    submit
  end

end
